groups: []
resources:
- name: src
  type: git
  source:
    uri: git@github.com:hpcloud/cf-plugin-backup.git
    branch: master
    private_key: {{git-private-key}}
- name: src-ci
  type: git
  source:
    uri: git@github.com:hpcloud/cf-plugin-backup-ci.git
    branch: master
    private_key: {{git-private-key}}
- name: s3.hcf-ci-concourse-cf-plugin-backup-master-linux
  type: s3
  source:
    region_name: us-west-2
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-hpe
    regexp: cf-plugin-backup-(.*)\.tgz
    private: true
- name: s3.hcf-ci-concourse-cf-plugin-backup-master-darwin
  type: s3
  source:
    region_name: us-west-2
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-hpe
    regexp: cf-plugin-backup-(.*)\.tgz
    private: true
- name: s3.hcf-ci-concourse-cf-plugin-backup-master-windows
  type: s3
  source:
    region_name: us-west-2
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-hpe
    regexp: cf-plugin-backup-(.*)\.tgz
    private: true
jobs:
- name: vet
  plan:
  - aggregate:
    - get: src-ci
      trigger: true
    - get: src
      trigger: true
  - task: vet
    file: src-ci/tasks/vet.yaml
- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: tools
    file: src-ci/tasks/tools.yaml
  - task: test
    file: src-ci/tasks/test.yaml
- name: lint
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: tools
    file: src-ci/tasks/tools.yaml
  - task: lint
    file: src-ci/tasks/lint.yaml
- name: format
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: tools
    file: src-ci/tasks/tools.yaml
  - task: format
    file: src-ci/tasks/format.yaml
- name: build
  plan:
  - aggregate:
    - get: src
      passed: [vet, lint, test]
      trigger: true
    - get: src-ci
      passed: [vet, lint, test]
      trigger: true
  - task: tools
    file: src-ci/tasks/tools.yaml
  - task: build
    file: src-ci/tasks/build.yaml
- name: dist
  plan:
  - aggregate:
    - get: src
      passed: [build]
      trigger: true
    - get: src-ci
      passed: [build]
      trigger: true
  - task: tools
    file: src-ci/tasks/tools.yaml
  - task: dist
    file: src-ci/tasks/dist.yaml
  - put: s3.hcf-ci-concourse-cf-plugin-backup-master-linux
    params:
      file: 'cf-plugin-backup/cf-plugin-backup-*-linux-*.tgz'
  - put: s3.hcf-ci-concourse-cf-plugin-backup-master-darwin
    params:
      file: 'cf-plugin-backup/cf-plugin-backup-*-darwin-*.tgz'
  - put: s3.hcf-ci-concourse-cf-plugin-backup-master-windows
    params:
      file: 'cf-plugin-backup/cf-plugin-backup-*-windows-*.tgz'