---
platform: linux
image: 'docker:///golang#1.6.2-wheezy'
inputs:
  - name: src
    path: src/github.com/hpcloud/cf-plugin-backup
  - name: src-ci
  - name: tools
    path: bin
outputs:
  - name: cf-plugin-backup
run:
  path: src/make/build
