---
platform: linux
image_resource: 
  type: docker-image
  source: 
    repository: golang
    tag: '1'
params:
  CGO_ENABLED: "0"
inputs:
  - name: src
    path: src/github.com/SUSE/cf-plugin-backup
  - name: src-ci
  - name: tools
    path: bin
outputs:
  - name: cf-plugin-backup
run:
  path: src-ci/scripts/dist.sh
