---
platform: linux
image_resource: 
  type: docker-image
  source: 
    repository: golang
    tag: '1.6.2-wheezy'
inputs:
  - name: src
    path: src/github.com/hpcloud/cf-plugin-backup
  - name: src-ci
run:
  path: src-ci/scripts/vet.sh
