---
platform: linux
image_resource: 
  type: docker-image
  source: 
    repository: golang
    tag: '1.7.3-wheezy'
inputs:
  - name: src
    path: src/github.com/SUSE/cf-plugin-backup
  - name: src-ci
run:
  path: src-ci/scripts/vet.sh
